/**
 * @file restart.hpp
 * --------------
 *
 * @brief HDF5 restart reader for .ath files
 *
 * @details Inverse of the writer in io.cpp. Reads scalars, vectors, and
 * Kokkos views back from an athelas .ath checkpoint and provides high-level
 * helpers to repopulate the grid, field arrays, composition, and ionization
 * state.
 */

#pragma once

#include <string>
#include <vector>

#include "H5Cpp.h"

#include "composition/compdata.hpp"
#include "geometry/grid.hpp"
#include "interface/state.hpp"
#include "io/io.hpp"
#include "kokkos_types.hpp"
#include "utils/error.hpp"

namespace athelas::io {

/**
 * @brief Read-only HDF5 reader for restart files.
 *
 * Mirrors the data primitives in HDF5Writer. Reads always go through a host
 * mirror before deep_copy to device, matching the writer's pattern.
 */
class RestartReader {
 public:
  explicit RestartReader(const std::string &filename);

  template <typename T>
  auto read_scalar(const std::string &path) const -> T;

  [[nodiscard]] auto read_string(const std::string &path) const -> std::string;

  template <typename T>
  auto read_vector(const std::string &path) const -> std::vector<T>;

  template <typename ViewType>
  void read_view(ViewType view, const std::string &path) const {
    static_assert(Kokkos::is_view<ViewType>::value,
                  "read_view expects a Kokkos::View");
    using value_type = typename ViewType::value_type;

    H5::DataSet ds = file_.openDataSet(path);
    H5::DataSpace space = ds.getSpace();
    const int ndims = space.getSimpleExtentNdims();
    if (ndims != static_cast<int>(view.rank())) {
      throw_athelas_error("Restart: rank mismatch reading " + path);
    }
    std::vector<hsize_t> dims(ndims);
    space.getSimpleExtentDims(dims.data());
    for (int r = 0; r < ndims; ++r) {
      if (dims[r] != static_cast<hsize_t>(view.extent(r))) {
        throw_athelas_error("Restart: extent mismatch reading " + path);
      }
    }

    using HostMirror = typename ViewType::HostMirror;
    HostMirror host = Kokkos::create_mirror_view(view);
    ds.read(host.data(), h5_predtype<value_type>());
    Kokkos::deep_copy(view, host);
  }

  [[nodiscard]] auto has(const std::string &path) const -> bool;
  [[nodiscard]] auto list_group(const std::string &group_path) const
      -> std::vector<std::string>;

  [[nodiscard]] auto has_attribute(const std::string &dataset_path,
                                   const std::string &attr_name) const -> bool;
  [[nodiscard]] auto read_string_attribute(const std::string &dataset_path,
                                           const std::string &attr_name) const
      -> std::string;

  /**
   * @brief Return the on-disk extents of a dataset, in HDF5 axis order.
   *
   * Useful for sizing C++ objects whose constructors need a dimension that
   * isn't a param (e.g., IonizationState's n_states comes from the last
   * extent of /ionization/ionization_fractions).
   */
  [[nodiscard]] auto dataset_extent(const std::string &dataset_path) const
      -> std::vector<hsize_t>;

  [[nodiscard]] auto file() const noexcept -> const H5::H5File & {
    return file_;
  }

 private:
  H5::H5File file_;
};

/**
 * @brief Read /info group into a SimInfo struct.
 */
auto load_info_from_h5(const RestartReader &reader) -> SimInfo;

/**
 * @brief Overwrite grid arrays (centers, widths, x_l, mass, mass_r, sqrt_gm,
 * nodal grid) from /mesh.
 */
void load_grid_from_h5(GridStructure &grid, const RestartReader &reader);

/**
 * @brief Repopulate registered field arrays from /fields (stage 0 for staged
 * fields). Skips "facedata", which is regenerated by the next hydro update.
 */
void load_fields_from_h5(const MeshState &mesh_state,
                         const RestartReader &reader);

/**
 * @brief Load composition data arrays from /composition into an existing
 * CompositionData. The species_indexer is restored from
 * /composition/species_indexer (preserving any pgen-specific aliases written
 * at dump time).
 */
void load_composition_from_h5(atom::CompositionData &comps,
                              const RestartReader &reader);

/**
 * @brief Load ionization arrays from /ionization into an existing
 * IonizationState.
 */
void load_ionization_from_h5(atom::IonizationState &ion,
                             const RestartReader &reader);

/**
 * @brief Populate a Params from /params. Dispatches by HDF5 datatype, using
 * the "param_kind" attribute on the dataset to recover std::array<double, N>
 * values (otherwise vector<double> of the same shape is indistinguishable).
 *
 * Does NOT add MethodID — it isn't directly serialized; callers should
 * re-derive from "time.integrator_string" via timestepper::string_to_id().
 */
void load_params_from_h5(Params &params, const RestartReader &reader);

} // namespace athelas::io
